version: "3.9"

services:

  db:
    image: postgres:16

    container_name: campusconnect_db

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  
  redis:

    image: redis:7-alpine

    container_name: campusconnect_redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command: redis-server --appendonly yes


  web:

    build:
      context: .

      dockerfile: Dockerfile

    container_name: campusconnect_api

    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy
      
      redis:
        condition: service_started

    env_file:
      - .env

    volumes:
      - .:/app

      - ./logs:/app/logs

      - ./media:/app/media

    ports:
      - "8000:8000"

    command: python manage.py runserver 0.0.0.0:8000

  celery:

    build: .

    container_name: campusconnect_celery

    restart: unless-stopped

    depends_on:

      db:
        condition: service_healthy

      redis:
        condition: service_started

    env_file:
      - .env

    volumes:
      - .:/app

    command: celery -A backend worker --loglevel=info --concurrency=4


  # celery-beat:

  #   build: .

  #   container_name: campusconnect_celery_beat

  #   restart: unless-stopped

  #   depends_on:

  #     redis:
  #       condition: service_started

  #     db:
  #       condition: service_healthy

  #   env_file:
  #     - .env

  #   volumes:
  #     - .:/app

  #   command: celery -A backend beat -l info   

volumes:

  postgres_data:

  redis_data: