# Generated by Django 6.0.6 on 2026-07-19 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('content_type', models.CharField(choices=[('listing', 'Listing'), ('review', 'Review'), ('user', 'User'), ('report', 'Report')], help_text='Type of content (listing, review, user)', max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('reason', models.TextField(help_text='Reason for flagging')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_items', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id'], name='moderator_f_content_361705_idx'), models.Index(fields=['is_resolved'], name='moderator_f_is_reso_f37a52_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModeratorAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('action_type', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('hide', 'Hide'), ('delete', 'Delete'), ('flag', 'Flag'), ('unflag', 'Unflag'), ('warning', 'Warning'), ('suspend', 'Suspend'), ('ban', 'Ban'), ('reinstate', 'Reinstate'), ('resolve_report', 'Resolve Report'), ('escalate', 'Escalate')], db_index=True, max_length=50)),
                ('content_type', models.CharField(choices=[('listing', 'Listing'), ('review', 'Review'), ('user', 'User'), ('report', 'Report')], help_text='Type of content acted upon (listing, review, user, report)', max_length=20)),
                ('content_id', models.PositiveIntegerField(help_text='ID of the content (listing_id, user_id, etc.)')),
                ('reason', models.TextField(blank=True, help_text='Reason for the action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra data (e.g., old status, new status, warning duration)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['moderator'], name='moderator_m_moderat_47df21_idx'), models.Index(fields=['action_type', 'created_at'], name='moderator_m_action__49bdc3_idx'), models.Index(fields=['content_type', 'content_id'], name='moderator_m_content_fe632b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModeratorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('content_type', models.CharField(choices=[('listing', 'Listing'), ('review', 'Review'), ('user', 'User'), ('report', 'Report')], max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('note', models.TextField()),
                ('is_private', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id'], name='moderator_m_content_4a7a2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
                ('ban_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Private notes for moderators')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['is_suspended'], name='moderator_u_is_susp_531f7c_idx'), models.Index(fields=['is_banned'], name='moderator_u_is_bann_ae7efc_idx')],
            },
        ),
    ]
