# Generated by Django 6.0.6 on 2026-07-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedcontent',
            name='content_type',
            field=models.CharField(choices=[('listing', 'Listing'), ('review', 'Review'), ('user', 'User'), ('report', 'Report'), ('category', 'Category'), ('hotspot', 'Hotspot')], help_text='Type of content (listing, review, user)', max_length=20),
        ),
        migrations.AlterField(
            model_name='moderatoraction',
            name='action_type',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('hide', 'Hide'), ('delete', 'Delete'), ('flag', 'Flag'), ('unflag', 'Unflag'), ('warning', 'Warning'), ('suspend', 'Suspend'), ('ban', 'Ban'), ('reinstate', 'Reinstate'), ('resolve_report', 'Resolve Report'), ('escalate', 'Escalate'), ('unhide', 'Unhide'), ('assign', 'Assign'), ('reopen', 'Reopen'), ('create', 'Create')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='moderatoraction',
            name='content_type',
            field=models.CharField(choices=[('listing', 'Listing'), ('review', 'Review'), ('user', 'User'), ('report', 'Report'), ('category', 'Category'), ('hotspot', 'Hotspot')], help_text='Type of content acted upon (listing, review, user, report)', max_length=20),
        ),
        migrations.AlterField(
            model_name='moderatornote',
            name='content_type',
            field=models.CharField(choices=[('listing', 'Listing'), ('review', 'Review'), ('user', 'User'), ('report', 'Report'), ('category', 'Category'), ('hotspot', 'Hotspot')], max_length=20),
        ),
    ]
