# Generated by Django 6.0.6 on 2026-07-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0002_alter_flaggedcontent_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatoraction',
            name='action_type',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('hide', 'Hide'), ('delete', 'Delete'), ('flag', 'Flag'), ('unflag', 'Unflag'), ('warning', 'Warning'), ('suspend', 'Suspend'), ('ban', 'Ban'), ('reinstate', 'Reinstate'), ('resolve_report', 'Resolve Report'), ('escalate', 'Escalate'), ('unhide', 'Unhide'), ('assign', 'Assign'), ('reopen', 'Reopen'), ('create', 'Create'), ('update', 'Update')], db_index=True, max_length=50),
        ),
    ]
