# Generated by Django 6.0.6 on 2026-07-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0003_alter_moderatoraction_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedcontent',
            name='content_type',
            field=models.CharField(choices=[('listing', 'Listing'), ('review', 'Review'), ('user', 'User'), ('report', 'Report'), ('category', 'Category'), ('hotspot', 'Hotspot'), ('lost_item', 'Lost Item')], help_text='Type of content (listing, review, user)', max_length=20),
        ),
        migrations.AlterField(
            model_name='moderatoraction',
            name='content_type',
            field=models.CharField(choices=[('listing', 'Listing'), ('review', 'Review'), ('user', 'User'), ('report', 'Report'), ('category', 'Category'), ('hotspot', 'Hotspot'), ('lost_item', 'Lost Item')], help_text='Type of content acted upon (listing, review, user, report)', max_length=20),
        ),
        migrations.AlterField(
            model_name='moderatornote',
            name='content_type',
            field=models.CharField(choices=[('listing', 'Listing'), ('review', 'Review'), ('user', 'User'), ('report', 'Report'), ('category', 'Category'), ('hotspot', 'Hotspot'), ('lost_item', 'Lost Item')], max_length=20),
        ),
    ]
