# Generated by Django 6.0.6 on 2026-08-14 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0004_alter_flaggedcontent_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flaggedcontent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Flagged Content', 'verbose_name_plural': 'Flagged Content'},
        ),
        migrations.AlterModelOptions(
            name='moderatoraction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Moderator Action', 'verbose_name_plural': 'Moderator Actions'},
        ),
        migrations.AlterModelOptions(
            name='moderatornote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Moderator Note', 'verbose_name_plural': 'Moderator Notes'},
        ),
        migrations.AlterModelOptions(
            name='usermoderation',
            options={'verbose_name': 'User Moderation', 'verbose_name_plural': 'User Moderations'},
        ),
        migrations.AlterField(
            model_name='flaggedcontent',
            name='content_id',
            field=models.PositiveIntegerField(help_text='ID of the content being flagged.'),
        ),
        migrations.AlterField(
            model_name='flaggedcontent',
            name='content_type',
            field=models.CharField(choices=[('listing', 'Listing'), ('review', 'Review'), ('user', 'User'), ('report', 'Report'), ('category', 'Category'), ('hotspot', 'Hotspot'), ('lost_item', 'Lost Item')], help_text='Type of content being flagged (listing, review, user).', max_length=20),
        ),
        migrations.AlterField(
            model_name='flaggedcontent',
            name='flagged_by',
            field=models.ForeignKey(help_text='The user who flagged the content.', on_delete=django.db.models.deletion.CASCADE, related_name='flagged_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flaggedcontent',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Whether the flag has been reviewed and resolved.'),
        ),
        migrations.AlterField(
            model_name='flaggedcontent',
            name='reason',
            field=models.TextField(help_text='Reason for flagging the content.'),
        ),
        migrations.AlterField(
            model_name='flaggedcontent',
            name='resolution_note',
            field=models.TextField(blank=True, help_text='Explanation of the resolution (e.g., content removed, warning issued).'),
        ),
        migrations.AlterField(
            model_name='flaggedcontent',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the flag was resolved.', null=True),
        ),
        migrations.AlterField(
            model_name='flaggedcontent',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Moderator who resolved the flag (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderatoraction',
            name='action_type',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('hide', 'Hide'), ('delete', 'Delete'), ('flag', 'Flag'), ('unflag', 'Unflag'), ('warning', 'Warning'), ('suspend', 'Suspend'), ('ban', 'Ban'), ('reinstate', 'Reinstate'), ('resolve_report', 'Resolve Report'), ('escalate', 'Escalate'), ('unhide', 'Unhide'), ('assign', 'Assign'), ('reopen', 'Reopen'), ('create', 'Create'), ('update', 'Update')], db_index=True, help_text='Type of moderation action (e.g., warning, suspend, delete, restore).', max_length=50),
        ),
        migrations.AlterField(
            model_name='moderatoraction',
            name='content_id',
            field=models.PositiveIntegerField(help_text='ID of the content (listing_id, user_id, review_id, etc.).'),
        ),
        migrations.AlterField(
            model_name='moderatoraction',
            name='content_type',
            field=models.CharField(choices=[('listing', 'Listing'), ('review', 'Review'), ('user', 'User'), ('report', 'Report'), ('category', 'Category'), ('hotspot', 'Hotspot'), ('lost_item', 'Lost Item')], help_text='Type of content acted upon (listing, review, user, report).', max_length=20),
        ),
        migrations.AlterField(
            model_name='moderatoraction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the moderator at the time of action.', null=True),
        ),
        migrations.AlterField(
            model_name='moderatoraction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extra data such as old status, new status, warning duration, etc.'),
        ),
        migrations.AlterField(
            model_name='moderatoraction',
            name='moderator',
            field=models.ForeignKey(help_text='The moderator who performed the action.', on_delete=django.db.models.deletion.CASCADE, related_name='moderator_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderatoraction',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for the action (optional).'),
        ),
        migrations.AlterField(
            model_name='moderatornote',
            name='author',
            field=models.ForeignKey(help_text='The moderator who wrote the note.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderatornote',
            name='content_id',
            field=models.PositiveIntegerField(help_text='ID of the content this note refers to.'),
        ),
        migrations.AlterField(
            model_name='moderatornote',
            name='content_type',
            field=models.CharField(choices=[('listing', 'Listing'), ('review', 'Review'), ('user', 'User'), ('report', 'Report'), ('category', 'Category'), ('hotspot', 'Hotspot'), ('lost_item', 'Lost Item')], help_text='Type of content the note is attached to (listing, review, user, etc.).', max_length=20),
        ),
        migrations.AlterField(
            model_name='moderatornote',
            name='is_private',
            field=models.BooleanField(default=True, help_text='If True, only moderators/admins can see this note. If False, visible to the content owner as well.'),
        ),
        migrations.AlterField(
            model_name='moderatornote',
            name='note',
            field=models.TextField(help_text='The actual note content.'),
        ),
        migrations.AlterField(
            model_name='usermoderation',
            name='ban_reason',
            field=models.TextField(blank=True, help_text='Reason for the permanent ban.'),
        ),
        migrations.AlterField(
            model_name='usermoderation',
            name='banned_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the user was banned.', null=True),
        ),
        migrations.AlterField(
            model_name='usermoderation',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Indicates if the user is permanently banned from the platform.'),
        ),
        migrations.AlterField(
            model_name='usermoderation',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Indicates if the user is currently suspended (temporarily blocked).'),
        ),
        migrations.AlterField(
            model_name='usermoderation',
            name='notes',
            field=models.TextField(blank=True, help_text='Private notes for moderators (not visible to the user).'),
        ),
        migrations.AlterField(
            model_name='usermoderation',
            name='suspended_until',
            field=models.DateTimeField(blank=True, help_text='Date and time when the suspension expires. If None, suspension is indefinite.', null=True),
        ),
        migrations.AlterField(
            model_name='usermoderation',
            name='user',
            field=models.OneToOneField(help_text='The user whose moderation status is tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermoderation',
            name='warning_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of active warnings issued to the user.'),
        ),
        migrations.AddIndex(
            model_name='moderatoraction',
            index=models.Index(fields=['moderator', 'created_at'], name='moderator_m_moderat_38d859_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoderation',
            index=models.Index(fields=['suspended_until'], name='moderator_u_suspend_2a5f50_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoderation',
            index=models.Index(fields=['is_suspended', 'suspended_until'], name='moderator_u_is_susp_ce80a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='usermoderation',
            constraint=models.CheckConstraint(condition=models.Q(('warning_count__gte', 0)), name='user_moderation_warning_count_non_negative'),
        ),
    ]
