# Generated by Django 6.0.6 on 2026-08-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0005_alter_flaggedcontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedcontent',
            name='content_type',
            field=models.CharField(choices=[('Listing', 'Listing'), ('Review', 'Review'), ('User', 'User'), ('Report', 'Report'), ('Category', 'Category'), ('Hotspot', 'Hotspot'), ('Lost Item', 'Lost Item')], help_text='Type of content being flagged (listing, review, user).', max_length=20),
        ),
        migrations.AlterField(
            model_name='moderatoraction',
            name='action_type',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject'), ('Hide', 'Hide'), ('Delete', 'Delete'), ('Flag', 'Flag'), ('Unflag', 'Unflag'), ('Warning', 'Warning'), ('Suspend', 'Suspend'), ('Ban', 'Ban'), ('Reinstate', 'Reinstate'), ('Resolve Report', 'Resolve Report'), ('Escalate', 'Escalate'), ('Unhide', 'Unhide'), ('Assign', 'Assign'), ('Reopen', 'Reopen'), ('Create', 'Create'), ('Update', 'Update')], db_index=True, help_text='Type of moderation action (e.g., warning, suspend, delete, restore).', max_length=50),
        ),
        migrations.AlterField(
            model_name='moderatoraction',
            name='content_type',
            field=models.CharField(choices=[('Listing', 'Listing'), ('Review', 'Review'), ('User', 'User'), ('Report', 'Report'), ('Category', 'Category'), ('Hotspot', 'Hotspot'), ('Lost Item', 'Lost Item')], help_text='Type of content acted upon (listing, review, user, report).', max_length=20),
        ),
        migrations.AlterField(
            model_name='moderatornote',
            name='content_type',
            field=models.CharField(choices=[('Listing', 'Listing'), ('Review', 'Review'), ('User', 'User'), ('Report', 'Report'), ('Category', 'Category'), ('Hotspot', 'Hotspot'), ('Lost Item', 'Lost Item')], help_text='Type of content the note is attached to (listing, review, user, etc.).', max_length=20),
        ),
    ]
