# Generated by Django 5.0.2 on 2026-05-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_average_rating_user_department_user_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hall_verified',
            field=models.BooleanField(default=False, help_text='Student hall/residence verified'),
        ),
    ]
