# Generated by Django 5.0.2 on 2026-05-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_hall_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter_name', models.CharField(help_text='Full name of the person reporting', max_length=255)),
                ('reporter_email', models.EmailField(help_text='UI email address', max_length=254)),
                ('issue_type', models.CharField(choices=[('report_listing', 'Report Listing'), ('report_user', 'Report User'), ('bug', 'Bug'), ('question', 'Question'), ('other', 'Other')], db_index=True, max_length=30)),
                ('listing_identifier', models.CharField(blank=True, help_text='Listing URL or title (for report_listing)', max_length=500, null=True)),
                ('reported_user_email', models.EmailField(blank=True, help_text='Email of the user being reported (for report_user)', max_length=254, null=True)),
                ('message', models.TextField(help_text='Detailed description of the issue')),
                ('is_reviewed', models.BooleanField(default=False, help_text='Admin has reviewed this report')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin')),
            ],
            options={
                'verbose_name': 'Contact / Report',
                'verbose_name_plural': 'Contact / Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
