# Generated by Django 5.0.2 on 2026-05-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_contactreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='badges/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_is_acti_ddda02_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='user_badges',
            field=models.ManyToManyField(blank=True, related_name='users_with_badge', to='users.badge'),
        ),
    ]
