# Generated by Django 5.0.2 on 2026-05-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_badge_remove_user_users_user_is_acti_ddda02_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matric_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_ids/'),
        ),
    ]
