# Generated by Django 5.0.2 on 2026-05-31 02:33

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_matric_number_alter_user_student_id_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=apps.users.models.token_expiry),
        ),
    ]
