# Generated by Django 5.0.2 on 2026-06-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_verificationtoken_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='transaction_count',
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='issue_type',
            field=models.CharField(choices=[('report_listing', 'Report Listing'), ('report_user', 'Report User'), ('bug', 'Bug'), ('question', 'Question'), ('other', 'Other'), ('account', 'Account')], db_index=True, max_length=30),
        ),
    ]
