# Generated by Django 5.0.2 on 2026-06-15 14:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_email_alter_verificationtoken_is_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('points', models.PositiveIntegerField(help_text='Number of points included in this package')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Nigerian Naira (₦)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(blank=True, help_text="Short description (e.g., 'Best value', 'Power seller')", max_length=100)),
                ('is_popular', models.BooleanField(default=False, help_text="Highlight this package as '🔥 Popular'")),
                ('is_best_value', models.BooleanField(default=False, help_text='Mark as best value for money')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which packages are displayed (lower first)')),
            ],
            options={
                'verbose_name': 'Point Package',
                'verbose_name_plural': 'Point Packages',
                'ordering': ['sort_order', 'points'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='PointPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('points_awarded', models.PositiveIntegerField(help_text="Number of points added to the user's balance")),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid in Naira', max_digits=10)),
                ('payment_reference', models.CharField(blank=True, help_text='Reference from payment gateway', max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the purchase was successfully completed', null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='users.pointpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point Purchase',
                'verbose_name_plural': 'Point Purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
