# Generated by Django 5.0.2 on 2026-06-19 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_pointpackage_user_points_pointpurchase_delete_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(help_text='Positive for addition, negative for subtraction.')),
                ('balance_after', models.PositiveIntegerField(help_text="The user's point balance after this transaction.")),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('listing_creation', 'Listing Creation'), ('reactivation', 'Reactivation'), ('badge_upgrade', 'Badge Upgrade'), ('promotion', 'Promotion'), ('admin_adjustment', 'Admin Adjustment'), ('transfer', 'Transfer'), ('refund', 'Refund'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('description', models.CharField(blank=True, help_text='Optional description of the transaction.', max_length=255)),
                ('reference', models.CharField(blank=True, help_text='Optional reference ID (e.g., listing_id, purchase_id).', max_length=100)),
                ('purchase', models.ForeignKey(blank=True, help_text='Link to the purchase if this transaction was from a purchase.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='users.pointpurchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point Transaction',
                'verbose_name_plural': 'Point Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='users_point_user_id_349536_idx'), models.Index(fields=['user', 'transaction_type'], name='users_point_user_id_56789a_idx'), models.Index(fields=['created_at'], name='users_point_created_d9a85f_idx')],
            },
        ),
    ]
