# Generated by Django 5.0.2 on 2026-06-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_pointtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointpurchase',
            name='gateway',
            field=models.CharField(blank=True, help_text='payment_gateway', max_length=200, null=True),
        ),
    ]
