# Generated by Django 5.0.2 on 2026-06-29 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_pointpurchase_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('account_creation_bonus', 'Account Creation Bonus'), ('purchase', 'Purchase'), ('listing_creation', 'Listing Creation'), ('reactivation', 'Reactivation'), ('badge_upgrade', 'Badge Upgrade'), ('promotion', 'Promotion'), ('admin_adjustment', 'Admin Adjustment'), ('transfer', 'Transfer'), ('refund', 'Refund'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
