# Generated by Django 5.0.2 on 2026-07-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_featureflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sold_items',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
