# Generated by Django 5.0.2 on 2026-07-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_sold_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('account_creation_bonus', 'Account Creation Bonus'), ('purchase', 'Purchase'), ('listing_creation', 'Listing Creation'), ('listing_update', 'Listing Update'), ('reactivation', 'Reactivation'), ('badge_upgrade', 'Badge Upgrade'), ('promotion', 'Promotion'), ('admin_adjustment', 'Admin Adjustment'), ('transfer', 'Transfer'), ('refund', 'Refund'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
    ]
