# Generated by Django 6.0.6 on 2026-07-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_pointtransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
