# Generated by Django 6.0.6 on 2026-07-14 12:15

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_badge_created_at_badge_created_by_badge_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture that will appear on all your product listings', null=True, upload_to=apps.users.models.profile_picture_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.student_id_upload_path),
        ),
    ]
