# Generated by Django 6.0.6 on 2026-07-19 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactreport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactreport',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactreport',
            name='escalated_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactreport',
            name='escalated_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactreport',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='contactreport',
            index=models.Index(fields=['status'], name='users_conta_status_2f4173_idx'),
        ),
        migrations.AddIndex(
            model_name='contactreport',
            index=models.Index(fields=['assigned_to'], name='users_conta_assigne_8a1aee_idx'),
        ),
        migrations.AddIndex(
            model_name='contactreport',
            index=models.Index(fields=['issue_type'], name='users_conta_issue_t_4a238e_idx'),
        ),
        migrations.AddIndex(
            model_name='contactreport',
            index=models.Index(fields=['reporter_email'], name='users_conta_reporte_f0962d_idx'),
        ),
    ]
