# Generated by Django 6.0.6 on 2026-07-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_backupcode_created_by_backupcode_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hall_verified_status',
            field=models.CharField(choices=[('active', 'Active'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id_verified_status',
            field=models.CharField(choices=[('active', 'Active'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
    ]
