# Generated by Django 6.0.6 on 2026-07-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_hall_verified_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_student_b7ecd1_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id_verified',
        ),
    ]
