# Generated by Django 6.0.6 on 2026-07-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_user_users_user_student_b7ecd1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id_verified',
            field=models.BooleanField(default=False),
        ),
    ]
