# Generated by Django 6.0.6 on 2026-07-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0030_user_student_id_verified'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['student_id_verified'], name='users_user_student_b7ecd1_idx'),
        ),
    ]
