# Generated by Django 6.0.6 on 2026-07-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_user_users_user_student_b7ecd1_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hall_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hall_residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hall_verified_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id_verified_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
    ]
