# Generated by Django 6.0.6 on 2026-07-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_user_hall_number_user_hall_residence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactormethod',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='twofactormethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
