# Generated by Django 6.0.6 on 2026-08-14 21:56

import apps.users.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0033_remove_twofactormethod_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupcode',
            options={'verbose_name': 'Backup Code', 'verbose_name_plural': 'Backup Codes'},
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.AlterModelOptions(
            name='featureflag',
            options={'ordering': ['name'], 'verbose_name': 'Feature Flag', 'verbose_name_plural': 'Feature Flags'},
        ),
        migrations.AlterModelOptions(
            name='twofactormethod',
            options={'verbose_name': 'Two‑Factor Method', 'verbose_name_plural': 'Two‑Factor Methods'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='verificationtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Verification Token', 'verbose_name_plural': 'Verification Tokens'},
        ),
        migrations.AddField(
            model_name='contactreport',
            name='escalated_by',
            field=models.ForeignKey(blank=True, help_text='Admin who escalated this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='backupcode',
            name='code_hash',
            field=models.CharField(help_text='Hashed backup code (for security, never store plaintext).', max_length=128),
        ),
        migrations.AlterField(
            model_name='backupcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the backup code was generated.'),
        ),
        migrations.AlterField(
            model_name='backupcode',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Whether this backup code has been used.'),
        ),
        migrations.AlterField(
            model_name='backupcode',
            name='user',
            field=models.ForeignKey(help_text='The user who owns these backup codes.', on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what the badge represents.', null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, help_text='Optional icon image for the badge.', null=True, upload_to='badges/'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(help_text="Name of the badge (e.g., 'Top Seller', 'Verified Student').", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes from admin.'),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Moderator assigned to handle this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='escalated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of escalation.', null=True),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='escalated_note',
            field=models.TextField(blank=True, help_text='Reason for escalation.'),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='escalated_to_admin',
            field=models.BooleanField(default=False, help_text='Whether this report was escalated to a higher admin level.'),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text='Admin has reviewed this report.'),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='issue_type',
            field=models.CharField(choices=[('report_listing', 'Report Listing'), ('report_user', 'Report User'), ('bug', 'Bug'), ('question', 'Question'), ('other', 'Other'), ('account', 'Account')], db_index=True, help_text='Category of the issue (e.g., report_listing, report_user, general_inquiry).', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='listing_identifier',
            field=models.CharField(blank=True, help_text='Listing URL or title (for report_listing).', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='message',
            field=models.TextField(help_text='Detailed description of the issue.'),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='reported_user_email',
            field=models.EmailField(blank=True, help_text='Email of the user being reported (for report_user).', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='reporter_email',
            field=models.EmailField(help_text='Email address of the person reporting.', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='reporter_name',
            field=models.CharField(help_text='Full name of the person reporting.', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Details of the resolution (e.g., action taken).'),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the report was resolved.', null=True),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Moderator who resolved this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='pending', help_text='Current status of the report (pending, in_progress, resolved, closed).', max_length=20),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the feature.'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the feature is globally active.'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='name',
            field=models.CharField(help_text="Feature name (e.g., 'dark_mode', 'listing_promotion').", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Optional per‑user override (if empty, feature applies globally).', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text='Optional URL to navigate to when the notification is clicked.', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether the notification has been read by the user.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(help_text='Full notification message.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('listing', 'Listing'), ('account', 'Account'), ('system', 'System'), ('transaction', 'Transaction'), ('others', 'Others')], db_index=True, default='others', help_text='Category of notification (order, listing, promotion, etc.).', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(help_text='Notification title/short summary.', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='The user who receives this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointpackage',
            name='description',
            field=models.CharField(blank=True, help_text="Short description (e.g., 'Best value', 'Power seller').", max_length=100),
        ),
        migrations.AlterField(
            model_name='pointpackage',
            name='is_best_value',
            field=models.BooleanField(default=False, help_text='Mark as best value for money.'),
        ),
        migrations.AlterField(
            model_name='pointpackage',
            name='is_popular',
            field=models.BooleanField(default=False, help_text="Highlight this package as '🔥 Popular'."),
        ),
        migrations.AlterField(
            model_name='pointpackage',
            name='points',
            field=models.PositiveIntegerField(help_text='Number of points included in this package.'),
        ),
        migrations.AlterField(
            model_name='pointpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in Nigerian Naira (₦).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pointpackage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which packages are displayed (lower first).'),
        ),
        migrations.AlterField(
            model_name='pointpurchase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid in Naira.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pointpurchase',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the purchase was successfully completed.', null=True),
        ),
        migrations.AlterField(
            model_name='pointpurchase',
            name='gateway',
            field=models.CharField(blank=True, help_text='Payment gateway used (e.g., paystack, flutterwave).', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pointpurchase',
            name='package',
            field=models.ForeignKey(help_text='The point package that was bought.', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='users.pointpackage'),
        ),
        migrations.AlterField(
            model_name='pointpurchase',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Reference from payment gateway (e.g., Paystack, Flutterwave).', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pointpurchase',
            name='points_awarded',
            field=models.PositiveIntegerField(help_text="Number of points added to the user's balance."),
        ),
        migrations.AlterField(
            model_name='pointpurchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Purchase status (pending, completed, failed, refunded).', max_length=20),
        ),
        migrations.AlterField(
            model_name='pointpurchase',
            name='user',
            field=models.ForeignKey(help_text='The user who made the purchase.', on_delete=django.db.models.deletion.CASCADE, related_name='point_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('account_creation_bonus', 'Account Creation Bonus'), ('purchase', 'Purchase'), ('listing_creation', 'Listing Creation'), ('listing_update', 'Listing Update'), ('reactivation', 'Reactivation'), ('badge_upgrade', 'Badge Upgrade'), ('promotion', 'Promotion'), ('admin_adjustment', 'Admin Adjustment'), ('transfer', 'Transfer'), ('refund', 'Refund'), ('other', 'Other')], db_index=True, default='other', help_text='Type of transaction (purchase, listing_promotion, refund, etc.).', max_length=30),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='user',
            field=models.ForeignKey(help_text='The user whose balance is affected.', on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='twofactormethod',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Whether this method is currently active.'),
        ),
        migrations.AlterField(
            model_name='twofactormethod',
            name='method',
            field=models.CharField(choices=[('totp', 'Totp'), ('sms', 'Sms'), ('email', 'Email'), ('hardware', 'Hardware'), ('backup', 'Backup')], help_text='2FA method (e.g., authenticator_app, sms, email).', max_length=20),
        ),
        migrations.AlterField(
            model_name='twofactormethod',
            name='secret',
            field=models.CharField(blank=True, help_text='Secret key or TOTP seed (if applicable).', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='twofactormethod',
            name='user',
            field=models.ForeignKey(help_text='The user who enabled this 2FA method.', on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating received from other users (0.0 to 5.0).', max_digits=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Academic department of the student.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text="User's primary email address (used for login).", max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email verification status (True if verified).'),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, help_text='Faculty to which the department belongs.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hall_number',
            field=models.CharField(blank=True, help_text='Room/hall number or block.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hall_residence',
            field=models.CharField(blank=True, help_text='Name of the student hall of residence.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hall_verified',
            field=models.BooleanField(default=False, help_text='Whether the student hall/residence has been verified.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hall_verified_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', help_text='Verification status of hall/residence (pending, approved, rejected).', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.PositiveIntegerField(blank=True, help_text='Year of study (e.g., 100, 200, 300, 400).', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='matric_number',
            field=models.CharField(blank=True, help_text='Student matriculation number (if applicable).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification',
            field=models.BooleanField(default=True, help_text='Whether the user wants to receive notifications.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Nigerian phone number (e.g., 08012345678 or +2348012345678).', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Nigerian number (e.g., 08012345678 or +2348012345678).', regex='^(?:\\+234|0)[789][01]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Current point balance (used for promoting listings, etc.).', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture that will appear on all your product listings.', null=True, upload_to=apps.users.models.profile_picture_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='sold_items',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Total number of items sold by this user.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id_photo',
            field=models.ImageField(blank=True, help_text='Photo of student ID for verification purposes.', null=True, upload_to=apps.users.models.student_id_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id_verified',
            field=models.BooleanField(default=False, help_text='Whether the student ID has been verified.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id_verified_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', help_text='Verification status of the student ID (pending, approved, rejected).', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Whether two‑factor authentication is enabled for this user.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_badges',
            field=models.ManyToManyField(blank=True, help_text='Badges earned by the user (e.g., for trust, activity, achievements).', related_name='users_with_badge', to='users.badge'),
        ),
        migrations.AlterField(
            model_name='user',
            name='visibility',
            field=models.BooleanField(default=True, help_text="Whether the user's profile is visible to others."),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=apps.users.models.token_expiry, help_text='Timestamp when the token expires.'),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the token has already been consumed.'),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='token',
            field=models.PositiveIntegerField(help_text='Six‑digit verification code.', unique=True),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='token_type',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('account_activation', 'Account Activation')], help_text='Purpose of token (e.g., email_verification, password_reset).', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='user',
            field=models.ForeignKey(help_text='The user for whom this token is generated.', on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='users_notif_is_read_316047_idx'),
        ),
        migrations.AddIndex(
            model_name='pointpurchase',
            index=models.Index(fields=['user'], name='users_point_user_id_4137a9_idx'),
        ),
        migrations.AddIndex(
            model_name='pointpurchase',
            index=models.Index(fields=['status'], name='users_point_status_66021b_idx'),
        ),
        migrations.AddIndex(
            model_name='pointpurchase',
            index=models.Index(fields=['user', 'status'], name='users_point_user_id_d95c60_idx'),
        ),
        migrations.AddConstraint(
            model_name='pointpackage',
            constraint=models.CheckConstraint(condition=models.Q(('points__gt', 0)), name='point_package_points_positive'),
        ),
        migrations.AddConstraint(
            model_name='pointpackage',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='point_package_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='pointpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('points_awarded__gt', 0)), name='point_purchase_awarded_positive'),
        ),
        migrations.AddConstraint(
            model_name='pointpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gt', 0)), name='point_purchase_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='pointtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='point_transaction_nonzero_amount'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('average_rating__gte', 0), ('average_rating__lte', 5)), name='user_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('points__gte', 0)), name='user_points_non_negative'),
        ),
    ]
