# Generated by Django 6.0.6 on 2026-08-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_backupcode_options_alter_badge_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactreport',
            name='issue_type',
            field=models.CharField(choices=[('Report Listing', 'Report Listing'), ('Report User', 'Report User'), ('Bug', 'Bug'), ('Question', 'Question'), ('Other', 'Other'), ('Account', 'Account')], db_index=True, help_text='Category of the issue (e.g., report_listing, report_user, general_inquiry).', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Review', 'In Review'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated')], default='Pending', help_text='Current status of the report (pending, in_progress, resolved, closed).', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Listing', 'Listing'), ('Account', 'Account'), ('System', 'System'), ('Transaction', 'Transaction'), ('Others', 'Others')], db_index=True, default='Others', help_text='Category of notification (order, listing, promotion, etc.).', max_length=255),
        ),
        migrations.AlterField(
            model_name='pointpurchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], db_index=True, default='Pending', help_text='Purchase status (pending, completed, failed, refunded).', max_length=20),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Account Creation Bonus', 'Account Creation Bonus'), ('Purchase', 'Purchase'), ('Listing Creation', 'Listing Creation'), ('Listing Update', 'Listing Update'), ('Reactivation', 'Reactivation'), ('Badge Upgrade', 'Badge Upgrade'), ('Promotion', 'Promotion'), ('Admin Adjustment', 'Admin Adjustment'), ('Transfer', 'Transfer'), ('Refund', 'Refund'), ('Other', 'Other')], db_index=True, default='Other', help_text='Type of transaction (purchase, listing_promotion, refund, etc.).', max_length=30),
        ),
        migrations.AlterField(
            model_name='twofactormethod',
            name='method',
            field=models.CharField(choices=[('TOTP', 'TOTP'), ('SMS', 'SMS'), ('Email', 'Email'), ('Hardware', 'Hardware'), ('Backup', 'Backup')], help_text='2FA method (e.g., authenticator_app, sms, email).', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='hall_verified_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', help_text='Verification status of hall/residence (pending, approved, rejected).', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id_verified_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', help_text='Verification status of the student ID (pending, approved, rejected).', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='token_type',
            field=models.CharField(choices=[('Email Verification', 'Email Verification'), ('Password Reset', 'Password Reset'), ('Account Activation', 'Account Activation')], help_text='Purpose of token (e.g., email_verification, password_reset).', max_length=50),
        ),
    ]
