# Generated by Django 6.0.6 on 2026-08-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_contactreport_issue_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Listing', 'Listing'), ('Account', 'Account'), ('System', 'System'), ('Notification', 'Notification'), ('Transaction', 'Transaction'), ('Others', 'Others')], db_index=True, default='Others', help_text='Category of notification (order, listing, promotion, etc.).', max_length=255),
        ),
    ]
