# Generated by Django 6.0.6 on 2026-08-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hall_verified_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], help_text='Verification status of hall/residence (pending, approved, rejected).', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id_verified_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], help_text='Verification status of the student ID (pending, approved, rejected).', max_length=50),
        ),
    ]
