# Generated by Django 6.0.6 on 2026-08-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_user_hall_verified_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hall_verified_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], help_text='Verification status of hall/residence (pending, approved, rejected).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id_verified_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], help_text='Verification status of the student ID (pending, approved, rejected).', max_length=50, null=True),
        ),
    ]
