# Generated by Django 6.0.6 on 2026-08-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_user_hall_verified_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional icon class (e.g., FontAwesome icon name).', max_length=50, null=True),
        ),
    ]
