# Generated by Django 6.0.6 on 2026-08-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_badge_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hall_verified_status_rejection_reason',
            field=models.CharField(blank=True, help_text='Reason for rejection', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id_verified_rejection_reason',
            field=models.CharField(blank=True, help_text='Reason for rejection', max_length=5000, null=True),
        ),
    ]
