# Generated by Django 6.0.6 on 2026-08-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_user_hall_verified_status_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactormethod',
            name='method',
            field=models.CharField(choices=[('Totp', 'Totp'), ('Sms', 'Sms'), ('Email', 'Email'), ('Hardware', 'Hardware'), ('Backup', 'Backup')], help_text='2FA method (e.g., authenticator_app, sms, email).', max_length=20),
        ),
    ]
