# Generated by Django 6.0.6 on 2026-08-16 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_twofactormethod_method'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contactreport',
            name='users_conta_reporte_f0962d_idx',
        ),
        migrations.RenameField(
            model_name='contactreport',
            old_name='reported_user_email',
            new_name='reported_details',
        ),
        migrations.AddField(
            model_name='contactreport',
            name='reporter',
            field=models.ForeignKey(blank=True, help_text='Person reporting.', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='issue_type',
            field=models.CharField(choices=[('Listing', 'Listing'), ('User', 'User'), ('Improve', 'Improve'), ('Support', 'Support')], db_index=True, help_text='Category of the issue (e.g., report_listing, report_user, general_inquiry).', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='listing_identifier',
            field=models.CharField(blank=True, help_text='the Reasons', max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='contactreport',
            name='reporter_email',
        ),
        migrations.RemoveField(
            model_name='contactreport',
            name='reporter_name',
        ),
    ]
