# Generated by Django 6.0.6 on 2026-08-16 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_remove_contactreport_users_conta_reporte_f0962d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactreport',
            name='reported_details',
        ),
        migrations.AddField(
            model_name='contactreport',
            name='reported_user_identifer',
            field=models.CharField(blank=True, help_text='Email/ID or anything of the user being reported (for report_user).', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactreport',
            name='reporter_email',
            field=models.EmailField(blank=True, help_text='Email of the reporter (for anonymous reports).', max_length=254),
        ),
        migrations.AddField(
            model_name='contactreport',
            name='reporter_name',
            field=models.CharField(blank=True, help_text='Name of the reporter (for anonymous reports).', max_length=150),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='listing_identifier',
            field=models.CharField(blank=True, help_text='Listing ID or title (for report_listing).', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='reporter',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who reported (null if anonymous).', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contactreport',
            index=models.Index(fields=['reporter_email'], name='users_conta_reporte_f0962d_idx'),
        ),
    ]
