# Generated by Django 6.0.6 on 2026-08-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_remove_contactreport_reported_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refferal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refferal_by',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refferal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
