# Generated by Django 5.0.2 on 2026-05-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
