# Generated by Django 5.0.2 on 2026-06-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_alter_listing_expires_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
