# Generated by Django 5.0.2 on 2026-06-02 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_delete_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listing',
            name='campus_list_status_1ed2f9_idx',
        ),
        migrations.AddIndex(
            model_name='campushotspot',
            index=models.Index(fields=['is_deleted', 'sort_order'], name='campus_camp_is_dele_10553a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_deleted', 'sort_order'], name='campus_cate_is_dele_b6e550_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['user', 'is_deleted'], name='campus_list_user_id_0b2e97_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'is_deleted'], name='campus_list_status_cf9059_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'expires_at', 'is_deleted'], name='campus_list_status_518b6d_idx'),
        ),
    ]
