# Generated by Django 5.0.2 on 2026-06-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_remove_listing_campus_list_status_1ed2f9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='badge',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('fair', 'Fair'), ('like_new', 'Like New'), ('bundle', 'Bundle'), ('almost_new', 'Almost New'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
