# Generated by Django 5.0.2 on 2026-06-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_lostandfound_claim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lostandfound',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('expired', 'Expired')], db_index=True, default='open', max_length=20),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['lost_item'], name='campus_clai_lost_it_a2ff9c_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['email'], name='campus_clai_email_15effd_idx'),
        ),
        migrations.AddIndex(
            model_name='lostandfound',
            index=models.Index(fields=['date_found', 'status'], name='campus_lost_date_fo_e76480_idx'),
        ),
        migrations.AddIndex(
            model_name='lostandfound',
            index=models.Index(fields=['email', 'status'], name='campus_lost_email_135068_idx'),
        ),
    ]
