# Generated by Django 5.0.2 on 2026-06-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0008_alter_claim_options_alter_lostandfound_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Lisiting_images/'),
        ),
    ]
