# Generated by Django 5.0.2 on 2026-06-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0009_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_ads_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_ads_banner_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_hot_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_hot_sales_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='badge',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('fair', 'Fair'), ('bundle', 'Bundle'), ('almost_new', 'Almost New'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sell'), ('wanted', 'Wanted'), ('freebie', 'Freebie'), ('service', 'Service')], default='sell', max_length=10),
        ),
    ]
