# Generated by Django 5.0.2 on 2026-06-18 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0010_listing_is_ads_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfound',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Nigerian number (e.g., 08012345678 or +2348012345678).', regex='^(?:\\+234|0)[789][01]\\d{8}$')]),
        ),
    ]
