# Generated by Django 5.0.2 on 2026-06-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0011_lostandfound_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfound',
            name='claimed_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
