# Generated by Django 5.0.2 on 2026-07-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0012_lostandfound_claimed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='auto_reactivate',
            field=models.BooleanField(default=False),
        ),
    ]
