# Generated by Django 6.0.6 on 2026-07-14 12:15

import apps.campus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0014_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.campus.models.listing_upload_path),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.campus.models.lost_and_found_upload_path),
        ),
    ]
