# Generated by Django 6.0.6 on 2026-07-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0015_alter_listing_image_alter_lostandfound_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('expired', 'Expired'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
