# Generated by Django 6.0.6 on 2026-07-19 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0016_alter_listing_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listing',
            name='campus_list_status_518b6d_idx',
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'is_deleted', 'expires_at'], name='listing_expire_idx'),
        ),
    ]
