# Generated by Django 6.0.6 on 2026-07-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0017_remove_listing_campus_list_status_518b6d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campushotspot',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('expired', 'Expired'), ('pending', 'Pending'), ('hidden', 'Hidden')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='campushotspot',
            index=models.Index(fields=['slug'], name='campus_camp_slug_20ed3c_idx'),
        ),
    ]
