# Generated by Django 6.0.6 on 2026-07-25 09:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0020_favorite_created_by_favorite_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Favourite',
        ),
        migrations.RenameIndex(
            model_name='favourite',
            new_name='campus_favo_user_id_b9ed2a_idx',
            old_name='campus_favo_user_id_1a8230_idx',
        ),
        migrations.RenameIndex(
            model_name='favourite',
            new_name='campus_favo_created_f4fc1b_idx',
            old_name='campus_favo_created_991a27_idx',
        ),
    ]
