# Generated by Django 6.0.6 on 2026-07-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0021_rename_favorite_favourite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('reject', 'Reject'), ('sold', 'Sold'), ('expired', 'Expired'), ('pending', 'Pending'), ('hidden', 'Hidden')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reject', 'Reject'), ('hide', 'Hidden'), ('open', 'Open'), ('claimed', 'Claimed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
    ]
