# Generated by Django 6.0.6 on 2026-08-14 21:56

import apps.campus.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0024_subcategory_listing_subcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(choices=[('rent_entire', 'Rent Entire Unit'), ('rent_room', 'Rent a Room (shared)'), ('roommate_wanted', 'Looking for Roommate')], default='rent_entire', help_text='Type of accommodation listing (entire unit, room, or roommate wanted).', max_length=20)),
                ('property_type', models.CharField(help_text='Type of property (e.g., Apartment, Hostel, House).', max_length=50)),
                ('bedrooms', models.PositiveIntegerField(default=1, help_text='Number of bedrooms.')),
                ('bathrooms', models.PositiveIntegerField(default=1, help_text='Number of bathrooms.')),
                ('furnished', models.BooleanField(default=False, help_text='Whether the property is furnished.')),
                ('rent_price', models.DecimalField(decimal_places=2, help_text='Monthly rent in Nigerian Naira (₦).', max_digits=10)),
                ('available_from', models.DateField(blank=True, help_text='Date from which the property is available.', null=True)),
                ('lease_duration', models.CharField(blank=True, help_text="Lease duration (e.g., '6 months', '1 year').", max_length=50, null=True)),
                ('electricity', models.BooleanField(default=False, help_text='Whether electricity is included/available.')),
                ('water', models.BooleanField(default=False, help_text='Whether water supply is available.')),
                ('security', models.BooleanField(default=False, help_text='Whether security is provided.')),
                ('parking', models.BooleanField(default=False, help_text='Whether parking space is available.')),
                ('distance_to_campus', models.CharField(blank=True, help_text="Distance to campus (e.g., '2km', '5 minutes walk').", max_length=50, null=True)),
                ('preferred_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Any')], help_text='Preferred gender of the roommate(s).', max_length=10, null=True)),
                ('preferred_student_type', models.CharField(blank=True, choices=[('UG', 'Undergrad'), ('G', 'Graduate'), ('A', 'Any')], help_text='Preferred type of student (undergrad, graduate, or any).', max_length=10, null=True)),
                ('max_occupants', models.PositiveIntegerField(default=1, help_text='Total number of people the room/unit can accommodate.')),
                ('roommate_notes', models.TextField(blank=True, help_text='Additional notes for potential roommates (e.g., habits, preferences).', null=True)),
            ],
            options={
                'verbose_name': 'Accommodation Listing Detail',
                'verbose_name_plural': 'Accommodation Listing Details',
            },
        ),
        migrations.CreateModel(
            name='SellListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price in Nigerian Naira (₦).', max_digits=10)),
                ('negotiation', models.BooleanField(default=False, help_text='Whether the price is negotiable.')),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('fair', 'Fair'), ('bundle', 'Bundle'), ('almost_new', 'Almost New'), ('other', 'Other')], help_text="Physical condition (e.g., 'New', 'Used - Like New', 'Fair').", max_length=50, null=True)),
                ('brand', models.CharField(blank=True, help_text='Brand of the product (e.g., Apple, Samsung).', max_length=100, null=True)),
                ('model', models.CharField(blank=True, help_text='Model name/number (e.g., iPhone 13, Galaxy S21).', max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of items available for sale.')),
                ('warranty', models.CharField(blank=True, help_text="Warranty information (e.g., '6 months', '1 year').", max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Sell Listing Detail',
                'verbose_name_plural': 'Sell Listing Details',
            },
        ),
        migrations.CreateModel(
            name='ServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Service price (optional – can be 'negotiable' or 'free').", max_digits=10, null=True)),
                ('negotiation', models.BooleanField(default=False, help_text='Whether the price is negotiable.')),
                ('delivery_time', models.CharField(blank=True, help_text="Estimated delivery or completion time (e.g., '2 days', '1 week').", max_length=100, null=True)),
                ('service_duration', models.CharField(blank=True, help_text="How long the service lasts (e.g., '1 hour', '3 months').", max_length=100, null=True)),
                ('experience', models.PositiveIntegerField(blank=True, help_text='Years of experience of the service provider.', null=True)),
                ('portfolio', models.URLField(blank=True, help_text='Link to a portfolio or previous work examples.', null=True)),
                ('online_available', models.BooleanField(default=False, help_text='Whether the service can be delivered online.')),
            ],
            options={
                'verbose_name': 'Service Listing Detail',
                'verbose_name_plural': 'Service Listing Details',
            },
        ),
        migrations.AlterModelOptions(
            name='campushotspot',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Campus Hotspot', 'verbose_name_plural': 'Campus Hotspots'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-created_at'], 'verbose_name': 'Claim', 'verbose_name_plural': 'Claims'},
        ),
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Favourite', 'verbose_name_plural': 'Favourites'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at'], 'verbose_name': 'Listing', 'verbose_name_plural': 'Listings'},
        ),
        migrations.AlterModelOptions(
            name='listinghotspot',
            options={'verbose_name': 'Listing Hotspot', 'verbose_name_plural': 'Listing Hotspots'},
        ),
        migrations.AlterModelOptions(
            name='lostandfound',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lost & Found Item', 'verbose_name_plural': 'Lost & Found Items'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='campus_list_categor_25676a_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='campus_list_price_f80639_idx',
        ),
        migrations.AlterField(
            model_name='campushotspot',
            name='description',
            field=models.CharField(blank=True, help_text='Brief description of the hotspot.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campushotspot',
            name='name',
            field=models.CharField(help_text="Name of the hotspot (e.g., 'Student Union', 'Library').", max_length=150),
        ),
        migrations.AlterField(
            model_name='campushotspot',
            name='slug',
            field=models.SlugField(help_text='URL‑friendly version of the name.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='campushotspot',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first).'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, help_text='Brief description of the category.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional icon class (e.g., FontAwesome icon name).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text="Category name (e.g., 'Electronics', 'Books').", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='URL‑friendly version of the name (auto‑generated).', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first).'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='answer1',
            field=models.CharField(help_text='Answer to the first verification question.', max_length=500),
        ),
        migrations.AlterField(
            model_name='claim',
            name='answer2',
            field=models.CharField(help_text='Answer to the second verification question.', max_length=500),
        ),
        migrations.AlterField(
            model_name='claim',
            name='email',
            field=models.EmailField(help_text='Email address of the claimant.', max_length=200),
        ),
        migrations.AlterField(
            model_name='claim',
            name='full_name',
            field=models.CharField(help_text='Full name of the person claiming the item.', max_length=200),
        ),
        migrations.AlterField(
            model_name='claim',
            name='lost_item',
            field=models.ForeignKey(help_text='The lost item being claimed.', on_delete=django.db.models.deletion.CASCADE, related_name='item_lost', to='campus.lostandfound'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number of the claimant.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Nigerian number (e.g., 08012345678 or +2348012345678).', regex='^(?:\\+234|0)[789][01]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='listing',
            field=models.ForeignKey(help_text='The listing that was favourited.', on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='campus.listing'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(help_text='The user who favourited the listing.', on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='auto_reactivate',
            field=models.BooleanField(default=False, help_text='Whether to automatically reactivate the listing after expiry.'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the item, service, or accommodation.', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this listing will automatically expire.', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='hotspots',
            field=models.ManyToManyField(help_text='Campus hotspots where this listing is relevant.', related_name='listings', through='campus.ListingHotspot', to='campus.campushotspot'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary image for the listing.', null=True, upload_to=apps.campus.models.listing_upload_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_ads_banner',
            field=models.BooleanField(default=False, help_text='Whether this listing appears as a banner ad.'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_ads_banner_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiry date for banner ad promotion.', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_hot_sales',
            field=models.BooleanField(default=False, help_text="Whether this listing is promoted as 'Hot Sales'."),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_hot_sales_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiry date for hot sales promotion.', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sell'), ('wanted', 'Wanted'), ('freebie', 'Freebie'), ('service', 'Service'), ('rent', 'Rent'), ('exchange', 'Exchange'), ('roommate', 'Roommate'), ('accommodation', 'Accommodation'), ('job', 'Job'), ('event', 'Event'), ('lost_found', 'Lost Found'), ('donation', 'Donation')], help_text='Type of listing (sell, wanted, service, accommodation).', max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('reject', 'Reject'), ('sold', 'Sold'), ('expired', 'Expired'), ('pending', 'Pending'), ('hidden', 'Hidden')], default='pending', help_text='Current status (pending, active, sold, expired, etc.).', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text='Short, descriptive title of the listing.', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(help_text='The user who created this listing.', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listinghotspot',
            name='hotspot',
            field=models.ForeignKey(help_text='The hotspot associated with this listing.', on_delete=django.db.models.deletion.CASCADE, to='campus.campushotspot'),
        ),
        migrations.AlterField(
            model_name='listinghotspot',
            name='listing',
            field=models.ForeignKey(help_text='The listing associated with this hotspot.', on_delete=django.db.models.deletion.CASCADE, to='campus.listing'),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='answer1',
            field=models.CharField(help_text='Correct answer to the first verification question.', max_length=500),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='answer2',
            field=models.CharField(help_text='Correct answer to the second verification question.', max_length=500),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='claimed_by',
            field=models.CharField(blank=True, help_text='Name of the person who claimed the item.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='date_found',
            field=models.DateField(help_text='Date the item was found.'),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='department',
            field=models.CharField(help_text='Academic department of the finder.', max_length=200),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='description',
            field=models.TextField(help_text='Detailed description of the item.'),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='email',
            field=models.EmailField(help_text='Email address of the finder.', max_length=200),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='full_name',
            field=models.CharField(help_text='Full name of the person who found the item.', max_length=200),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image of the item.', null=True, upload_to=apps.campus.models.lost_and_found_upload_path),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='item_name',
            field=models.CharField(help_text='Name of the lost/found item.', max_length=200),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='location',
            field=models.CharField(help_text='Where the item was lost or found.', max_length=500),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number of the finder.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Nigerian number (e.g., 08012345678 or +2348012345678).', regex='^(?:\\+234|0)[789][01]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reject', 'Reject'), ('hide', 'Hidden'), ('open', 'Open'), ('claimed', 'Claimed'), ('expired', 'Expired')], db_index=True, default='pending', help_text='Current status (pending, claimed, resolved).', max_length=20),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='verification1',
            field=models.CharField(help_text='First verification question (to prove ownership).', max_length=500),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='verification2',
            field=models.CharField(help_text='Second verification question.', max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional textual feedback.', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='from_user',
            field=models.ForeignKey(help_text='The user who wrote the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(blank=True, help_text='The listing being reviewed (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='campus.listing'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='to_user',
            field=models.ForeignKey(help_text='The user who received the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(help_text='Parent category this subcategory belongs to.', on_delete=django.db.models.deletion.RESTRICT, related_name='subcategories', to='campus.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.CharField(blank=True, help_text='Brief description of the subcategory.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional icon class (e.g., FontAwesome icon name).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(help_text="Subcategory name (e.g., 'Laptops', 'Fiction').", max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(help_text='URL‑friendly version of the name.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within the parent category.'),
        ),
        migrations.AddConstraint(
            model_name='lostandfound',
            constraint=models.CheckConstraint(condition=models.Q(('date_found__lte', datetime.date(2026, 8, 14))), name='lost_found_date_not_future'),
        ),
        migrations.AddField(
            model_name='accommodationlisting',
            name='listing',
            field=models.OneToOneField(help_text='The base listing this accommodation detail belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_details', to='campus.listing'),
        ),
        migrations.AddField(
            model_name='selllisting',
            name='category',
            field=models.ForeignKey(help_text='Category of the product for sale.', on_delete=django.db.models.deletion.RESTRICT, related_name='sell_listings', to='campus.category'),
        ),
        migrations.AddField(
            model_name='selllisting',
            name='listing',
            field=models.OneToOneField(help_text='The base listing this sell detail belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sell_details', to='campus.listing'),
        ),
        migrations.AddField(
            model_name='selllisting',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Optional subcategory for finer classification.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sell_listings', to='campus.subcategory'),
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='category',
            field=models.ForeignKey(help_text='Category of the service.', on_delete=django.db.models.deletion.RESTRICT, related_name='service_listings', to='campus.category'),
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='listing',
            field=models.OneToOneField(help_text='The base listing this service detail belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='campus.listing'),
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Optional subcategory for the service.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='service_listings', to='campus.subcategory'),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='subcategory',
        ),
        migrations.AddIndex(
            model_name='accommodationlisting',
            index=models.Index(fields=['purpose'], name='campus_acco_purpose_b47098_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodationlisting',
            index=models.Index(fields=['property_type'], name='campus_acco_propert_11eaaf_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodationlisting',
            index=models.Index(fields=['rent_price'], name='campus_acco_rent_pr_59fef4_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodationlisting',
            index=models.Index(fields=['bedrooms'], name='campus_acco_bedroom_9414da_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodationlisting',
            index=models.Index(fields=['furnished'], name='campus_acco_furnish_2d98c4_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodationlisting',
            index=models.Index(fields=['available_from'], name='campus_acco_availab_57fa15_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodationlisting',
            index=models.Index(fields=['distance_to_campus'], name='campus_acco_distanc_39cb9d_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodationlisting',
            index=models.Index(fields=['preferred_gender'], name='campus_acco_preferr_9fb7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodationlisting',
            index=models.Index(fields=['preferred_student_type'], name='campus_acco_preferr_d9129e_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodationlisting',
            index=models.Index(fields=['purpose', 'rent_price'], name='campus_acco_purpose_4bb7da_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodationlisting',
            index=models.Index(fields=['property_type', 'furnished'], name='campus_acco_propert_4a9805_idx'),
        ),
        migrations.AddConstraint(
            model_name='accommodationlisting',
            constraint=models.CheckConstraint(condition=models.Q(('rent_price__gt', 0)), name='accommodation_rent_positive'),
        ),
        migrations.AddConstraint(
            model_name='accommodationlisting',
            constraint=models.CheckConstraint(condition=models.Q(('bedrooms__gte', 1)), name='accommodation_bedrooms_min'),
        ),
        migrations.AddConstraint(
            model_name='accommodationlisting',
            constraint=models.CheckConstraint(condition=models.Q(('bathrooms__gte', 1)), name='accommodation_bathrooms_min'),
        ),
        migrations.AddConstraint(
            model_name='accommodationlisting',
            constraint=models.CheckConstraint(condition=models.Q(('max_occupants__gte', 1)), name='accommodation_max_occupants_min'),
        ),
        migrations.AddIndex(
            model_name='selllisting',
            index=models.Index(fields=['category'], name='campus_sell_categor_de12c0_idx'),
        ),
        migrations.AddIndex(
            model_name='selllisting',
            index=models.Index(fields=['price'], name='campus_sell_price_78fedc_idx'),
        ),
        migrations.AddIndex(
            model_name='selllisting',
            index=models.Index(fields=['negotiation'], name='campus_sell_negotia_124dff_idx'),
        ),
        migrations.AddIndex(
            model_name='selllisting',
            index=models.Index(fields=['condition'], name='campus_sell_conditi_be705a_idx'),
        ),
        migrations.AddIndex(
            model_name='selllisting',
            index=models.Index(fields=['brand'], name='campus_sell_brand_a7534e_idx'),
        ),
        migrations.AddIndex(
            model_name='selllisting',
            index=models.Index(fields=['model'], name='campus_sell_model_cee98c_idx'),
        ),
        migrations.AddIndex(
            model_name='selllisting',
            index=models.Index(fields=['category', 'price'], name='campus_sell_categor_359496_idx'),
        ),
        migrations.AddIndex(
            model_name='selllisting',
            index=models.Index(fields=['brand', 'model'], name='campus_sell_brand_f8b925_idx'),
        ),
        migrations.AddConstraint(
            model_name='selllisting',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='sell_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='selllisting',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='sell_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['category'], name='campus_serv_categor_ba9a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['subcategory'], name='campus_serv_subcate_a76fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['price'], name='campus_serv_price_50d4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['negotiation'], name='campus_serv_negotia_b34ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['delivery_time'], name='campus_serv_deliver_c2ca35_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['online_available'], name='campus_serv_online__f957ce_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['category', 'price'], name='campus_serv_categor_344dfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicelisting',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0), ('price__isnull', True), _connector='OR'), name='service_price_non_negative_or_null'),
        ),
    ]
