# Generated by Django 6.0.6 on 2026-08-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0025_accommodationlisting_selllisting_servicelisting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sell'), ('wanted', 'Wanted'), ('freebie', 'Freebie'), ('service', 'Service'), ('rent', 'Rent'), ('exchange', 'Exchange'), ('roommate', 'Roommate'), ('accommodation', 'Accommodation'), ('job', 'Job'), ('event', 'Event'), ('lost_found', 'Lost Found'), ('donation', 'Donation')], help_text='Category type (e.g., sell, wanted, service, accommodation).', max_length=100, null=True),
        ),
    ]
