# Generated by Django 6.0.6 on 2026-08-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0026_category_listing_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lostandfound',
            name='lost_found_date_not_future',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='campus_cate_name_44d603_idx',
        ),
        migrations.AlterField(
            model_name='accommodationlisting',
            name='purpose',
            field=models.CharField(choices=[('Rent Entire Unit', 'Rent Entire Unit'), ('Rent a Room (Shared)', 'Rent a Room (Shared)'), ('Looking for Roommate', 'Looking for Roommate')], default='Rent Entire Unit', help_text='Type of accommodation listing (entire unit, room, or roommate wanted).', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='listing_type',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Service', 'Service'), ('Accommodation', 'Accommodation')], help_text='Category type (e.g., sell, wanted, service, accommodation).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Service', 'Service'), ('Accommodation', 'Accommodation')], help_text='Type of listing (sell, wanted, service, accommodation).', max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Reject', 'Reject'), ('Sold', 'Sold'), ('Expired', 'Expired'), ('Pending', 'Pending'), ('Hidden', 'Hidden')], default='Pending', help_text='Current status (pending, active, sold, expired, etc.).', max_length=10),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reject', 'Reject'), ('Hidden', 'Hidden'), ('Open', 'Open'), ('Claimed', 'Claimed'), ('Expired', 'Expired')], db_index=True, default='Pending', help_text='Current status (pending, claimed, resolved).', max_length=20),
        ),
        migrations.AlterField(
            model_name='selllisting',
            name='condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Fair', 'Fair'), ('Bundle', 'Bundle'), ('Almost New', 'Almost New'), ('Other', 'Other')], help_text="Physical condition (e.g., 'New', 'Used - Like New', 'Fair').", max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['listing_type'], name='campus_cate_listing_91f6ff_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name', 'listing_type'], name='campus_cate_name_c148bf_idx'),
        ),
    ]
