# Generated by Django 6.0.6 on 2026-08-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0027_remove_lostandfound_lost_found_date_not_future_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfound',
            name='answer1',
            field=models.CharField(help_text='Correct answer to the first verification question.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='answer2',
            field=models.CharField(help_text='Correct answer to the second verification question.', max_length=500, null=True),
        ),
    ]
