# Generated by Django 6.0.6 on 2026-08-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0029_alter_lostandfound_answer1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationlisting',
            name='preferred_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], help_text='Preferred gender of the roommate(s).', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accommodationlisting',
            name='preferred_student_type',
            field=models.CharField(blank=True, choices=[('Undergrad', 'Undergrad'), ('Graduate', 'Graduate'), ('Any', 'Any')], help_text='Preferred type of student (undergrad, graduate, or any).', max_length=10, null=True),
        ),
    ]
