# Generated by Django 6.0.6 on 2026-08-23 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(db_index=True, help_text="Title of the poll (e.g., 'Class President Election 2026').", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the poll, its purpose, and rules.')),
                ('start_date', models.DateTimeField(blank=True, help_text='When voting begins. If null, voting starts immediately upon publishing.', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When voting ends. If null, the poll never expires.', null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='When the poll was published (made active/visible).', null=True)),
                ('max_votes_per_voter', models.PositiveIntegerField(default=1, help_text='Maximum votes each student can cast in this poll. Default is 1.')),
                ('allow_self_voting', models.BooleanField(default=True, help_text='If True, contestants can vote for themselves.')),
                ('is_anonymous', models.BooleanField(default=True, help_text='If True, no one can see who voted for whom.')),
                ('results_visibility', models.CharField(choices=[('Visible to All (Live)', 'Visible to All (Live)'), ('Visible After Voting', 'Visible After Voting'), ('Hidden Until Poll Ends', 'Hidden Until Poll Ends'), ('Visible to Admins Only', 'Visible to Admins Only'), ('Visible to Contestants Only', 'Visible to Contestants Only')], db_index=True, default='Visible to All (Live)', help_text='When and who can see results.', max_length=50)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Upcoming', 'Upcoming'), ('Active', 'Active'), ('Ended', 'Ended')], db_index=True, default='Draft', help_text='Current status of the poll.', max_length=20)),
                ('qr_code_url', models.CharField(blank=True, help_text='URL/path to the generated QR code image for this poll.', max_length=500)),
                ('total_votes_cast', models.PositiveIntegerField(default=0, help_text='Running total of all votes cast in this poll (cached for performance).')),
                ('total_contestants', models.PositiveIntegerField(default=0, help_text='Total number of contestants in this poll (cached for performance).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra data such as poll settings, configuration flags, etc.')),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which contestants appear in the poll (0 = first).')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Withdrawn', 'Withdrawn')], db_index=True, default='Active', help_text='Status of the contestant (Active or Withdrawn).', max_length=20)),
                ('vote_count', models.PositiveIntegerField(default=0, help_text='Total votes this contestant has received (cached for performance).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra data such as campaign promises, tags, etc.')),
                ('student', models.ForeignKey(help_text='The registered student who is a contestant.', on_delete=django.db.models.deletion.CASCADE, related_name='contestant_entries', to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(help_text='The poll this student is contesting in.', on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='vote.poll')),
            ],
            options={
                'verbose_name': 'Contestant',
                'verbose_name_plural': 'Contestants',
                'ordering': ['display_order', '-vote_count'],
            },
        ),
        migrations.CreateModel(
            name='PollCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(db_index=True, help_text='Name of the category (e.g., Student Elections, Awards, Competitions).', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this category represents.')),
                ('color_code', models.CharField(blank=True, help_text='Hex color code for UI styling (e.g., #FF5733).', max_length=7)),
                ('icon', models.CharField(blank=True, help_text="Icon name for UI display (e.g., 'vote', 'award', 'trophy').", max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this category is active and visible.')),
            ],
            options={
                'verbose_name': 'Poll Category',
                'verbose_name_plural': 'Poll Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'is_active'], name='vote_pollca_name_af1984_idx'), models.Index(fields=['created_at'], name='vote_pollca_created_fda77f_idx')],
            },
        ),
        migrations.AddField(
            model_name='poll',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this poll belongs to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to='vote.pollcategory'),
        ),
        migrations.CreateModel(
            name='PollResultCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('vote_count', models.PositiveIntegerField(default=0, help_text='Total votes received by this contestant at the time of caching.')),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of total votes (e.g., 45.67%).', max_digits=5)),
                ('rank', models.PositiveIntegerField(default=0, help_text='Rank/position of this contestant (1st, 2nd, etc.).')),
                ('contestant', models.ForeignKey(help_text='The contestant these results belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='cached_results', to='vote.contestant')),
                ('poll', models.ForeignKey(help_text='The poll these results belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='cached_results', to='vote.poll')),
            ],
            options={
                'verbose_name': 'Poll Result Cache',
                'verbose_name_plural': 'Poll Result Caches',
                'ordering': ['rank', '-vote_count'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the vote was cast.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra data such as device info, tracking, etc.')),
                ('contestant', models.ForeignKey(help_text='The contestant who received this vote.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='vote.contestant')),
                ('poll', models.ForeignKey(help_text='The poll in which this vote was cast.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='vote.poll')),
                ('voter', models.ForeignKey(help_text='The student who cast this vote.', on_delete=django.db.models.deletion.CASCADE, related_name='cast_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ['-voted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contestant',
            index=models.Index(fields=['poll', 'student'], name='vote_contes_poll_id_004616_idx'),
        ),
        migrations.AddIndex(
            model_name='contestant',
            index=models.Index(fields=['poll', 'display_order'], name='vote_contes_poll_id_0bb537_idx'),
        ),
        migrations.AddIndex(
            model_name='contestant',
            index=models.Index(fields=['poll', '-vote_count'], name='vote_contes_poll_id_d7a3bb_idx'),
        ),
        migrations.AddIndex(
            model_name='contestant',
            index=models.Index(fields=['student', 'created_at'], name='vote_contes_student_5d4219_idx'),
        ),
        migrations.AddIndex(
            model_name='contestant',
            index=models.Index(fields=['poll', 'status'], name='vote_contes_poll_id_672c93_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contestant',
            unique_together={('poll', 'student')},
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['status', 'created_at'], name='vote_poll_status_78d4b7_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['category', 'status'], name='vote_poll_categor_4ba908_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['created_at'], name='vote_poll_created_927a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['start_date', 'end_date'], name='vote_poll_start_d_8e20fd_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='vote_poll_status_e8787d_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['published_at', 'status'], name='vote_poll_publish_77e3a7_idx'),
        ),
        migrations.AddIndex(
            model_name='pollresultcache',
            index=models.Index(fields=['poll', 'rank'], name='vote_pollre_poll_id_ba57f8_idx'),
        ),
        migrations.AddIndex(
            model_name='pollresultcache',
            index=models.Index(fields=['poll', '-vote_count'], name='vote_pollre_poll_id_097ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='pollresultcache',
            index=models.Index(fields=['contestant'], name='vote_pollre_contest_bdb37d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pollresultcache',
            unique_together={('poll', 'contestant')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['poll', 'voter'], name='vote_vote_poll_id_c538fd_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['poll', 'contestant'], name='vote_vote_poll_id_edecf7_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter', 'voted_at'], name='vote_vote_voter_i_6b4373_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['poll', 'voter', 'voted_at'], name='vote_vote_poll_id_afbe3e_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['contestant', '-voted_at'], name='vote_vote_contest_fe1f70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'voter')},
        ),
    ]
